// ============================================================
// data.js — Datos de los temas de primeros auxilios
// ============================================================

const TOPICS = [
  {
    id: 'rcp',
    icon: '❤️',
    iconBg: '#fdecea',
    title: 'RCP y paro cardíaco',
    subtitle: 'Reanimación Cardiopulmonar',
    urgency: 'alta',
    urgencyLabel: 'Alta urgencia',
    desc: 'Cuando el corazón deja de latir, cada segundo cuenta. La RCP puede duplicar o triplicar las probabilidades de supervivencia.',
    steps: [
      'Verifica que la escena sea segura y llama al 123.',
      'Revisa si la persona respira (máx. 10 segundos).',
      'Pon el talón de tu mano en el centro del pecho.',
      'Comprimir fuerte y rápido: 100–120 veces/min, 5 cm de profundidad.',
      'Si sabes RCP completa: 30 compresiones + 2 respiraciones. Repite.',
      'No pares hasta que llegue ayuda o la persona recupere el pulso.',
    ],
    warning: '⚠ No mover a la víctima',
    stepColor: { bg: '#fdecea', text: '#D62828' },
  },
  {
    id: 'heridas',
    icon: '🩸',
    iconBg: '#fdecea',
    title: 'Heridas y hemorragias',
    subtitle: 'Control de sangrado',
    urgency: 'alta',
    urgencyLabel: 'Alta urgencia',
    desc: 'El sangrado excesivo puede llevar al shock en minutos. La presión directa es tu mejor aliado.',
    steps: [
      'Usa guantes o una bolsa plástica si los tienes.',
      'Aplica presión directa con una tela limpia o gasa.',
      'Mantén la presión continua por al menos 10 minutos.',
      'Si el trapo se empapa, agrega más encima — no retires el primero.',
      'Eleva el miembro herido si es posible (reduce el flujo).',
      'Si el sangrado no cede en 15 min, llama al 123 urgente.',
    ],
    warning: '⚠ No retirar objetos incrustados',
    stepColor: { bg: '#fdecea', text: '#D62828' },
  },
  {
    id: 'quemaduras',
    icon: '🔥',
    iconBg: '#fff7e6',
    title: 'Quemaduras',
    subtitle: 'Primeros pasos ante el calor',
    urgency: 'media',
    urgencyLabel: 'Urgencia media',
    desc: 'La reacción en los primeros 10 minutos determina la gravedad de una quemadura. Actúa con calma.',
    steps: [
      'Retira la fuente de calor y aleja a la persona del peligro.',
      'Enfría con agua fría corriente (no helada) por 10–20 minutos.',
      'Retira ropa y joyas del área (si no están pegadas a la piel).',
      'Cubre con una gasa estéril o tela limpia ligeramente húmeda.',
      'No revientes ampollas ni apliques cremas, aceites o hielo.',
      'Quemaduras >5 cm o en cara/manos/genitales: ir a urgencias.',
    ],
    warning: '⚠ Nunca usar hielo directo',
    stepColor: { bg: '#fff7e6', text: '#b45309' },
  },
  {
    id: 'fracturas',
    icon: '🦴',
    iconBg: '#e8f5ee',
    title: 'Fracturas y esguinces',
    subtitle: 'Inmovilización y soporte',
    urgency: 'media',
    urgencyLabel: 'Urgencia media',
    desc: 'Una inmovilización incorrecta puede empeorar la lesión. El principio RICE es tu guía principal.',
    steps: [
      '<strong>R</strong>eposo: inmoviliza la zona afectada inmediatamente.',
      '<strong>I</strong>ce (hielo): aplica frío envuelto en tela, nunca directo.',
      '<strong>C</strong>ompresión: vendaje suave (no cortar circulación).',
      '<strong>E</strong>levación: mantén el miembro por encima del corazón.',
      'Sospecha de fractura: inmovilizar con férula improvisada.',
      'No intentar "acomodar" el hueso. Buscar atención médica.',
    ],
    warning: '⚠ No mover fracturas de columna',
    stepColor: { bg: '#e8f5ee', text: '#2D6A4F' },
  },
  {
    id: 'atragantamiento',
    icon: '🫁',
    iconBg: '#fdecea',
    title: 'Atragantamiento',
    subtitle: 'Maniobra de Heimlich',
    urgency: 'alta',
    urgencyLabel: 'Alta urgencia',
    desc: 'El atragantamiento puede causar muerte en minutos. La maniobra de Heimlich es efectiva en adultos y niños mayores de 1 año.',
    steps: [
      'Pregunta "¿Te estás atragantando?". Si no puede hablar, actúa.',
      'Párate detrás de la persona, inclínala ligeramente hacia adelante.',
      'Da 5 golpes secos en la espalda (entre los omóplatos).',
      'Rodea su cintura, coloca el puño sobre el ombligo.',
      'Jala con fuerza hacia adentro y arriba (5 veces).',
      'Alterna golpes y compresiones hasta que expulse el objeto.',
    ],
    warning: '⚠ Bebés: técnica diferente',
    stepColor: { bg: '#fdecea', text: '#D62828' },
  },
  {
    id: 'desmayos',
    icon: '😵',
    iconBg: '#f0f4ff',
    title: 'Desmayos y convulsiones',
    subtitle: 'Pérdida de consciencia',
    urgency: 'media',
    urgencyLabel: 'Urgencia media',
    desc: 'La calma es clave. Proteger a la persona y garantizar su vía aérea es lo primero.',
    steps: [
      '<strong>Desmayo:</strong> acomoda a la persona en el suelo con cuidado.',
      'Eleva las piernas 30 cm para mejorar el flujo al cerebro.',
      '<strong>Convulsión:</strong> despeja el área de objetos peligrosos.',
      'Coloca algo suave bajo su cabeza. No sujetes sus movimientos.',
      'Nunca pongas nada en su boca. Espera que pase la convulsión.',
      'Si dura >5 min o no recupera consciencia: llama al 123.',
    ],
    warning: '⚠ Nunca meter dedos en la boca',
    stepColor: { bg: '#f0f4ff', text: '#3b5bdb' },
  },
  {
    id: 'picaduras',
    icon: '🐝',
    iconBg: '#f5f0ff',
    title: 'Picaduras y mordeduras',
    subtitle: 'Reacciones e infecciones',
    urgency: 'baja',
    urgencyLabel: 'Baja urgencia',
    desc: 'La mayoría son leves, pero la reacción alérgica severa (anafilaxia) es una emergencia. Aprende a diferenciarlas.',
    steps: [
      'Aleja a la persona del animal o insecto.',
      'Lava la zona con agua y jabón por al menos 5 minutos.',
      'Retira el aguijón (si aplica) raspando con tarjeta, no pellizques.',
      'Aplica hielo envuelto para reducir inflamación (15 min).',
      'Señales de anafilaxia: dificultad para respirar, hinchazón en garganta → 123 ya.',
      'Mordedura animal: lavar bien y acudir a urgencias (riesgo de rabia).',
    ],
    warning: '⚠ Anafilaxia = emergencia',
    stepColor: { bg: '#f5f0ff', text: '#6741d9' },
  },
];

const KIT_ITEMS = [
  { icon: '🩹', label: 'Gasas y vendas estériles' },
  { icon: '✂️', label: 'Tijeras de punta roma' },
  { icon: '🧤', label: 'Guantes de látex (x4)' },
  { icon: '🌡️', label: 'Termómetro digital' },
  { icon: '💊', label: 'Analgésico básico' },
  { icon: '🧴', label: 'Antiséptico (povidona)' },
  { icon: '📏', label: 'Tablillas (férulas)' },
  { icon: '🔦', label: 'Linterna con pilas extra' },
  { icon: '📋', label: 'Lista de teléfonos de emergencia' },
  { icon: '💉', label: 'Suero oral de rehidratación' },
];

const SEARCH_KEYWORDS = {
  rcp:           'RCP y paro cardíaco — sigue los 6 pasos del protocolo.',
  corazón:       'RCP y paro cardíaco — actúa en menos de 4 minutos.',
  paro:          'RCP y paro cardíaco — llama al 123 y empieza compresiones.',
  sangr:         'Heridas y hemorragias — presión directa es lo primero.',
  hemorrag:      'Heridas y hemorragias — no retires el objeto incrustado.',
  herida:        'Heridas y hemorragias — lava, presiona, eleva.',
  quemad:        'Quemaduras — agua fría corriente por 10–20 min. Nunca hielo.',
  fuego:         'Quemaduras — aleja la fuente de calor primero.',
  fractur:       'Fracturas — aplica RICE: Reposo, Hielo, Compresión, Elevación.',
  hueso:         'Fracturas — inmoviliza sin intentar "acomodar" el hueso.',
  esguince:      'Esguinces — RICE y consulta médica si hay mucho dolor.',
  atragant:      'Atragantamiento — 5 golpes en la espalda + 5 compresiones abdominales.',
  heimlich:      'Maniobra de Heimlich — alterna golpes y compresiones abdominales.',
  desmay:        'Desmayos — acuesta a la persona y eleva las piernas.',
  convul:        'Convulsiones — protege la cabeza, no sujetes, no pongas nada en la boca.',
  picad:         'Picaduras — lava, aplica frío, observa signos de anafilaxia.',
  mordedura:     'Mordeduras — lava con agua y jabón y acude a urgencias.',
  alergi:        'Posible anafilaxia — dificultad para respirar → llama al 123 ya.',
  anafilax:      'Anafilaxia — emergencia grave. Llama al 123 inmediatamente.',
  kit:           'Kit básico — desplázate hacia abajo para ver la lista de elementos.',
};
